speed_limit:
  reporters:
    pmb2_web:
      type: reem_topic
  limiters:
    base_laser:
      type: laser
      topic: scan
      disabled: false
      obstacle_max_dist: 1.5
      stop_dist: 0.05   #padding around the footprint
      speed_factor: 0.5
      fixed: true
