<?xml version="1.0"?>

<!--
  Copyright (c) 2014, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find pmb2_description)/urdf/wheels/wheel.transmission.xacro"/>
  <xacro:include filename="$(find pmb2_description)/urdf/wheels/wheel.gazebo.xacro"/>

  <xacro:macro name="wheel" params="side reflect radius width torque velocity separation parent">
    <link name="wheel_${side}_link">
      <!--
      <inertial>
        <origin xyz="0 0 ${-0.00207 * reflect}" rpy="0 0 0"/>
        <mass value="1.82362"/>
        <inertia ixx="0.00499743171" ixy="${ 0.00000004464 * reflect}" ixz="-0.00000002245"
                 iyy="0.00499741733" iyz="${-0.00000000164 * reflect}"
                 izz="0.00839239692"/>
      </inertial>
      -->

      <!-- The wheels are modelled as discs, with diameter 0.1962 and thickness 0.04-->
      <xacro:inertial_cylinder_with_pose mass="1.82362" diameter="${2.0*radius}" z_height="${width}">
        <origin xyz="0.0 0.0 ${-0.00207 * reflect}" rpy="0 0 0" />
      </xacro:inertial_cylinder_with_pose> 

      <visual>
        <origin xyz="0 0 0" rpy="${-90.0 * (1 - reflect) * deg_to_rad} 0 0"/>
        <geometry>
          <mesh filename="package://pmb2_description/meshes/wheels/wheel.stl"/>
        </geometry>
        <material name="DarkGrey"/>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>

        <!--
        Set friction for the wheels:

        Note: The friction directions were buggy in Gazebo until June2017.

        mu: Friction co-efficient tangent to the contact normal.
        mu2: Friction co-efficient for the other tangent.
        fdir1: Direction of mu1 in the collision local reference frame, otherwise defaults to x-axis of world reference frame.
        slip1: Force dependent slip direction.

        Available parameters:
        http://sdformat.org/spec?ver=1.5&elem=collision#surface_friction

        Links to more documentation:
        http://answers.gazebosim.org/question/13083/explain-gazebo-friction-coefficients-mu-and-mu2/
        -->
          <!-- was 0.1 and 0.001 when robot base was 4kg

 
        <surface>
          <friction>
            <ode>
              <mu>10.0</mu> 
              <mu2>0.001</mu2>
              <fdir1>1 0 0</fdir1>
              <slip1>0.0</slip1>
              <slip2>0.0</slip2>
            </ode>
          </friction>
        </surface>

 -->
      </collision>

    </link>

    <joint name="wheel_${side}_joint" type="continuous">
      <parent link="${parent}_link"/>
      <child link="wheel_${side}_link"/>
      <origin xyz="0 ${-separation / 2 * reflect} 0" rpy="${-90.0 * deg_to_rad} 0 0"/>
      <axis xyz="0 0 1"/>
      <limit effort="${torque}" velocity="${velocity / radius}"/>

      <!-- Add some friction to the axles -->

      <dynamics friction="1.0" damping="0.0" />

    </joint>

    <!-- Transmission -->
    <xacro:wheel_transmission side="${side}"/>

    <!-- Gazebo extensions -->
    <xacro:wheel_gazebo side="${side}"/>
  </xacro:macro>
</robot>
